# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi Welcome to my blog~!
email: Lim.Hannah0228@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We've been waiting for you a long time and everyone is really happy that you could make it! This blog's source code is hosted on my GitHub where you are welcome to file a bug or clone my repo and contribute <3
baseurl: "/schemes_and_machinations" # the subpath of your site, e.g. /blog
url: "https://limh0228.github.io/schemes_and_machinations" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
